---
name: "OwnTone"
description: "OwnTone add-on for Home Assistant"
version: 28.6-ls115
slug: owntone
arch:
  - aarch64
audio: true
host_network: true
ports:
  3688/tcp: 3688
  6600/tcp: 6600
  5353/tcp: 5353
  3689/tcp: 3689
  3690/udp: 3690
  3691/udp: 3691
ports_description:
  3688/tcp: Websockets
  6600/tcp: MPD
  5353/tcp: Avahi
  3689/tcp: DAAP
  3690/udp: "Control Port - Airplay"
  3691/udp: "Timing Port - Airplay"
image: lscr.io/linuxserver/daapd
startup: services
privileged: true
webui: "http://[HOST]:[PORT:3689]/"
